### ISSUE TITLE
Only recounts sales not earnings

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/EDD-Recount-Earnings#7]
Not 100% positive that I'm interpreting this functionality correctly but am working to answer this ticket: https://easydigitaldownloads.com/support/topic/recount-earnings-resets-individual-sales-count-but-not-individual-earnings/

In my tests, I made purchases in test mode, then went to individual products and hit Recount Earnings. This changed the Sales value reset to 0 but the Earnings remained the same.

Also, the global Recount Earnings tool didn't do anything on my tests.

I also tried using https://wordpress.org/plugins/transients-manager/ and deleting transients relating to sales made no difference. Ideas?

**Comment by pippinsplugins** [comment]
It should recount both.

Let me know if you still need help with this.

**Comment by flowdee** [comment]
The downloads overview still shows 1 sale and 67 EUR earnings but everything is deleted.

**Comment by pippinsplugins** [comment]
@flowdee I've seen multiple reports of that. We're getting ready to do some enhancements to the plugin that should resolve this.
